title: Kagoshima University Student Observatory
description: 宇宙の感動を分かち合い、天文学のコミュニティを育てる学生主体の場です。
logo: /assets/images/logo_20251115_scienceclub.png
show_downloads: false
markdown: kramdown

github:
  is_project_page: false
