title: Kagoshima University Student Observatory
description: 学生が観測を通して宇宙の驚きと感動を分かち合い、地域や支援者とともに天文学のコミュニティを育てる場です。 / A student-led place to share the wonder of the universe and to grow an astronomy community together with the public and supporters.
theme: jekyll-theme-minimal
logo: /assets/images/logo_20251115_scienceclub.png
show_downloads: false
markdown: kramdown

github:
  is_project_page: false
